export const CONSTANTS = {
  // Cards total in game depending on difficulty
  cardsCount: 0,

  points: {
    success: 7,
    total: 0,
  },
  
  // Difficulty user can choose in the game
  difficulties: {
    easy: 20,
    medium: 30,
    hard: 50,
  },

  // Images URL to set in back cards
  backCardImagesUrl: [
    "card-background.jpg",
    "card-background-2.jpg",
    "card-background-3.jpg",
    "card-background-4.jpg",
    "card-background-5.jpg",
    "card-background-6.jpg",
    "card-background-7.jpg",
    "card-background-9.jpg",
  ],

  // Default category - to set images URL in front cards
  defaultImagesURL: [
    "4-icons.png",
    "4-squares.png",
    "a-letter.png",
    "airplane.png",
    "android.jpg",
    "animated-search.png",
    "bluetooth.jpg",
    "bus.png",
    "camera.png",
    "cinema.png",
    "clock.png",
    "cloud-sun.jpg",
    "decoration.png",
    "earth-virus.png",
    "eye.png",
    "flower-black-white.png",
    "globe-airplane.jpg",
    "globe-grafit.png",
    "gu-grafit.png",
    "h-letter.png",
    "hands-washed.png",
    "idea.png",
    "instagram.jpg",
    "light.jpg",
    "man-head.png",
    "medicine-icons.png",
    "mountains.png",
    "musical-note.png",
    "notification.jpg",
    "pen.png",
    "people.png",
    "person.png",
    "pixeled-heart.png",
    "search.png",
    "telephone.png",
    "thumb.png",
    "virus.png",
    "w.png",
    "whatsapp.jpg",
    "www.png",
  ],

  // Emojis category - set images URL in front cards 
  emojiImagesURL: [
    "emoji-1.jpg",
    "emoji-2.jpg",
    "emoji-3.jpg",
    "emoji-4.jpg",
    "emoji-5.jpg",
    "emoji-6.jpg",
    "emoji-7.jpg",
    "emoji-8.jpg",
    "emoji-9.jpg",
    "emoji-10.jpg",
    "emoji-11.jpg",
    "emoji-12.jpg",
    "emoji-13.png",
    "emoji-14.jpg",
    "emoji-15.jpg",
    "emoji-16.jpg",
    "emoji-17.jpg",
    "emoji-18.png",
    "emoji-19.jpg",
    "emoji-20.png",
    "emoji-21.jpg",
    "emoji-22.jpg",
    "emoji-23.jpg",
    "emoji-24.jpg",
    "emoji-25.jpg",
    "emoji-26.jpg",
    "emoji-27.jpg",
    "emoji-28.jpg",
    "emoji-29.jpg",
    "emoji-30.jpg",
    "emoji-31.jpg",
    "emoji-32.png",
  ],
};
